twig:
    paths:
        '%kernel.project_dir%/templates': default
        '%kernel.project_dir%/src/Newsletter/Resource/templates': newsletter
        '%kernel.project_dir%/src/Mailer/Resource/templates': mailer
