twig:
    paths:
        '%kernel.project_dir%/templates': default
        '%kernel.project_dir%/src/Newsletter/Resources/templates': newsletter
        '%kernel.project_dir%/src/Mailing/Resources/templates': newsletter
