---
version: '3'

services:
  web:
    image: registry.made.dev/docker/alpine-nginx-php7:0.4
    # change this to the image of the actual project, currently it just shows to the base image
    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - ${EXPOSED_PORT-80}:8000
    environment:
      - APP_ENV=${APP_ENV-dev}
      - DOCUMENT_ROOT=${DOCUMENT_ROOT-/var/www/html/}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT-512M}
      - MAILER_URL=${MAILER_URL-none}
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  database:
    image: mariadb
    restart: always
#    ports:
#      - 3306:3306
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog_website
      MYSQL_USER: blog_website
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database

volumes:
  database-data: